services:
    warthog:
        build:
            context: ../
        container_name: warthog-stress-test-scripts
        networks:
            - warthog_stress_test
        environment:
            REDIS_HOST: 'warthog-stress-test-redis'
        depends_on:
            redis:
                condition: service_started
    redis:
        image: redis:7.0.11-alpine
        container_name: warthog-stress-test-redis
        tmpfs: /data
        ports:
            - 6379:6379
        networks:
            - warthog_stress_test

networks:
    warthog_stress_test:
